### ISSUE TITLE
Unable to verify the first certificate with "axios", "got" works.

### ISSUE THREAD

**Issue by frekac** [rangav/thunder-client-support#1413]
**Describe the bug**

After the update the default "axios" http library produce:
"Unable to verify the first certificate"

Certificates are produced by internal CA.

Changing http library setting to "got" solves the issue.

**To Reproduce**
Only had to update the client with the new axios library and sending a request to an api.

**Expected behavior**
Problem solved by changing back to "got" but if "got" will be deprecated then axios would need to work.

**Platform:** 
 - OS:  Windows 10 
 - vscode version: 1.84.2
 - extension version: 2.16.0

**Are you using the free version/paid version/trial:**
free

**Comment by rangav** [comment]
Hi @frekac Thanks for the feedback.

We will only remove `got` if all the problems are resolved with `axios`. Till then we support both libraries.

Is your backend code based on nodejs?

**Comment by rangav** [comment]
Can you do a test with axios yourself and see which config is working for you in the **Post Request scripting**.

sample script below:
```js
const axios = require('axios');
var result = await axios.get("your website url");
console.log(result.data);
```

useful links
https://www.codewithyou.com/blog/how-to-use-axios-to-handle-ssltls-certificate-verification-errors-in-nodejs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#execute-requests

**Comment by KayRitzmann** [comment]
i have also problems with self singed certificates. Working before. got not accepting https anymore.

![grafik](https://github.com/rangav/thunder-client-support/assets/79902340/a4d8915d-5d88-41a7-adee-8beb0151b517)

**Comment by rangav** [comment]
@KayRitzmann thanks for reporting the issue, can you please do this test - https://github.com/rangav/thunder-client-support/issues/1413#issuecomment-1814229381

**Comment by KayRitzmann** [comment]
> @KayRitzmann thanks for reporting the issue, can you please do this test - [#1413 (comment)](https://github.com/rangav/thunder-client-support/issues/1413#issuecomment-1814229381)

{
    "message": "self-signed certificate",
    "name": "Error",
    "stack": "Error: self-signed certificate
        at AxiosError.from (D:\\Projects\\VS_Code\\testaxios\\node_modules\\axios\\dist\\node\\axios.cjs:837:14)
        at RedirectableRequest.handleRequestError (D:\\Projects\\VS_Code\\testaxios\\node_modules\\axios\\dist\\node\\axios.cjs:3083:25)
        at RedirectableRequest.emit (node:events:513:28)
        at eventHandlers.<computed> (D:\\Projects\\VS_Code\\testaxios\\node_modules\\follow-redirects\\index.js:14:24)
        at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)
        at TLSSocket.emit (node:events:513:28)
        at emitErrorNT (node:internal/streams/destroy:151:8)
        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "User-Agent": "Thunder Client (https://www.thunderclient.com)",
            "X-RPC-Auth-Username": "",
            "X-RPC-Auth-Password": "",
            "Content-Length": "347",
            "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "method": "post",
        "url": "https://172.17.72.80/src/jsonrpc.php",
        "data": "[{\"version\":\"2.0\",\"method\":\"cmdb.objects.read\",\"params\":{\"filter\":{\"title\":\"DLW-PVZM32879\"},\"limit\":\"0,10\",\"order_by\":\"title\",\"sort\":\"ASC\",\"apikey\":\"\",\"language\":\"en\"},\"id\":1},{\"version\":\"2.0\",\"method\":\"cmdb.category.read\",\"params\":{\"objID\":60,\"category\":\"C__CATS__FILE_ACTUAL\",\"apikey\":\"\",\"language\":\"en\"},\"id\":2}]"
    },
    "code": "DEPTH_ZERO_SELF_SIGNED_CERT",
    "status": null
}

**Comment by rangav** [comment]
Thanks @KayRitzmann for testing

can you test again with below code

```js
const https = require('https')

// certificate issue fix 
const agent = new https.Agent({
  rejectUnauthorized: false,
  requestCert: true,
})

const axios = require('axios');

// pass agent here
var result = await axios.get("your website url", {
    httpsAgent: agent,
  });


console.log(result.data);
```

**Comment by KayRitzmann** [comment]
> Thanks @KayRitzmann for testing
> 
> can you please test again with below code
> 
> ```js
> const https = require('https')
> const axios = require('axios');
> 
> // certificate issue fix 
> const agent = new https.Agent({
>   rejectUnauthorized: false,
>   requestCert: false,
> })
> 
> // pass agent here
> var result = await axios.get("your website url", {
>     httpsAgent: agent,
>   });
> 
> 
> console.log(result.data);
> ```

this works

**Comment by rangav** [comment]
Super thanks - One last test

can you please remove this line - `requestCert: false` and test again.

**Comment by frekac** [comment]
> Can you do a test with axios yourself and see which config is working for you in the **Post Request scripting**.
> 
> sample script below:
> 
> ```js
> const axios = require('axios');
> var result = await axios.get("your website url");
> console.log(result.data);
> ```
> 
> useful links https://www.codewithyou.com/blog/how-to-use-axios-to-handle-ssltls-certificate-verification-errors-in-nodejs https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#execute-requests

Not sure what you mean about the question in regard to nodejs,
Just doing a simple GET call to an API, the API itself is based on C#.

Tested the code you provided in all the examples, all of them produce the same error message as my original post.
Tried the scripts in Tests->Scripting->Inline script in the Thunderclient extension.

**Comment by KayRitzmann** [comment]
> Super thanks - One last test
> 
> can you please remove this line - `requestCert: false` and test again.

also works

**Comment by rangav** [comment]
Thanks @KayRitzmann for confirmation.

**Comment by rangav** [comment]
I have fixed the bug - Can you please install the extension and confirm its working with `axios`?

[vscode-thunder-client-2.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/13378632/vscode-thunder-client-2.16.1.vsix.zip)

**Comment by frekac** [comment]
Unfortunately it produce the same issue. Api calls to other services work so I'll see if I can find something on my end.

**Comment by frekac** [comment]
Checked the certificates for one site that works and the one with a problem. The one with a problem have a wildcard certificate. Not sure if that is the issue but maybe something to look into.

**Comment by brbecker** [comment]
We also saw this issue today. Where we saw it used a cert which was not self-signed, but signed by our internal corporate CA. It is a wildcard cert.

**Comment by rangav** [comment]
I have created sample project for testing axios config related is self certificate. Please test and let me know which config is working for you.

https://github.com/rangav/axios-test

**Comment by felimoles** [comment]
back to 2.15.3 version, go to extension, click "uninstall" and select "install another version" 

work for me, using vscode + docker + traefik

**Comment by Wavewash** [comment]
Also had to revert to 2.15.3 to get self signed certs to work. Thanks @felimoles

**Comment by rangav** [comment]
Hi All, I made the small config chnages to address this issue for axios.

Can you guys please update extension to `v2.16.1`  and let me know if its working or not?

**Comment by rangav** [comment]
I have changed back the default http library from `axios` to `got`. Please update to `v2.16.2`

**Comment by Wavewash** [comment]
Was able to test and confirm v2.16.2 works! Thank you! @rangav

**Comment by chezsmithy** [comment]
@rangav with the latest release moving to axios it appears that certificates loaded in the global config are no longer working. Curious if this issue has been re-introduced?

**Comment by rangav** [comment]
@chezsmithy Thanks for the feedback, We will review and fix it. 
Temporarily you change the http library to `got`

<img width="754" height="211" alt="Image" src="https://github.com/user-attachments/assets/c9a8b840-f800-4efd-ac39-17e43d48089c" />
