### ISSUE TITLE
Does not work with Arch Linux (Code 1.61.1)

### ISSUE THREAD

**Issue by camposFabio** [rangav/thunder-client-support#371]
**Describe the bug**
When I try to make an request nothing happens

**To Reproduce**
From Command Palette (Cm+Sh+P) type thunder and select Thunder Client: New Request

**Expected behavior**
Open the Thunder-client page

**Platform:** 
 - OS:  Linux arch 5.14.12-arch1-1 x86_64 GNU/Linux
 - vscode version: 1.61.1
 - extension version: v1.9.1

**Solution:**

TraceLog:
﻿
log.ts:289  INFO Starting extension host with pid 28950.
log.ts:301   ERR [Extension Host] (node:28950) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:28950) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'findOne' of undefined
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'findOne' of undefined
	at Function.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:210277)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209607
	at new Promise (<anonymous>)
	at n (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209352)
	at Function.da (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:210222)
	at Function.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:164099)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163496
	at new Promise (<anonymous>)
	at n (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163241)
	at Function.Et (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:164048)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8370)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
	at t.default.jt (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8184)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8838)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
	at t.default.bt (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8504)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7783)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
	at t.default.Ce (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7526)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:4319)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1499
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1244)
	at t.default.je (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:4068)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:3568)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1499
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1244)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:3523
	at l._executeContributedCommand (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111652)
	at l.$executeContributedCommand (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:112090)
	at i._doInvokeHandler (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13802)
	at i._invokeHandler (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13486)
	at i._receiveRequest (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12148)
	at i._receiveOneMessage (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10826)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8922
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30514
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at u._receiveMessage (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21260)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18138
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at v.acceptChunk (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13351)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12699
	at Socket.w (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13465)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'findOne' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'findOne' of undefined
	at Function.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at n (vscode-file://vscode…dist/extension.js:1)
	at Function.da (vscode-file://vscode…dist/extension.js:1)
	at Function.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at n (vscode-file://vscode…dist/extension.js:1)
	at Function.Et (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at t.default.jt (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at t.default.bt (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at t.default.Ce (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at t.default.je (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at vscode-file://vscode…dist/extension.js:1
	at l._executeContributedCommand (vscode-file://vscode…onHostProcess.js:94)
	at l.$executeContributedCommand (vscode-file://vscode…onHostProcess.js:94)
	at i._doInvokeHandler (vscode-file://vscode…onHostProcess.js:98)
	at i._invokeHandler (vscode-file://vscode…onHostProcess.js:98)
	at i._receiveRequest (vscode-file://vscode…onHostProcess.js:98)
	at i._receiveOneMessage (vscode-file://vscode…onHostProcess.js:98)
	at vscode-file://vscode…onHostProcess.js:98
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at l.fire (vscode-file://vscode…onHostProcess.js:74)
	at vscode-file://vscode…nHostProcess.js:113
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at l.fire (vscode-file://vscode…onHostProcess.js:74)
	at u._receiveMessage (vscode-file://vscode…onHostProcess.js:74)
	at vscode-file://vscode…onHostProcess.js:74
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at v.acceptChunk (vscode-file://vscode…onHostProcess.js:74)
	at vscode-file://vscode…onHostProcess.js:74
	at Socket.w (vscode-file://vscode…nHostProcess.js:113)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'find' of undefined
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'find' of undefined
	at Function.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209903)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209607
	at new Promise (<anonymous>)
	at n (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209352)
	at Function.an (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209848)
	at Function.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:165913)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163496
	at new Promise (<anonymous>)
	at n (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163241)
	at Function.Ta (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:165848)
	at Function.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:166507)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163496
	at new Promise (<anonymous>)
	at n (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163241)
	at Function.xt (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:166447)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8064)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
	at t.default.yt (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7924)
	at t.default.<anonymous> (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7879)
	at Generator.next (<anonymous>)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
	at new Promise (<anonymous>)
	at s (/home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
	at /home/fabio/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7822
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at u._updateViewState (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:83413)
	at r.$onDidChangeWebviewPanelViewStates (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:84799)
	at i._doInvokeHandler (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13802)
	at i._invokeHandler (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13486)
	at i._receiveRequest (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12148)
	at i._receiveOneMessage (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10826)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8922
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30514
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at u._receiveMessage (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21260)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18138
	at a.fire (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at v.acceptChunk (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13351)
	at /home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12699
	at Socket.w (/home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13465)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'find' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'find' of undefined
	at Function.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at n (vscode-file://vscode…dist/extension.js:1)
	at Function.an (vscode-file://vscode…dist/extension.js:1)
	at Function.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at n (vscode-file://vscode…dist/extension.js:1)
	at Function.Ta (vscode-file://vscode…dist/extension.js:1)
	at Function.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at n (vscode-file://vscode…dist/extension.js:1)
	at Function.xt (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at t.default.yt (vscode-file://vscode…dist/extension.js:1)
	at t.default.<anonymous> (vscode-file://vscode…dist/extension.js:1)
	at Generator.next (<anonymous>)
	at vscode-file://vscode…dist/extension.js:1
	at new Promise (<anonymous>)
	at s (vscode-file://vscode…dist/extension.js:1)
	at vscode-file://vscode…dist/extension.js:1
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at u._updateViewState (vscode-file://vscode…onHostProcess.js:95)
	at r.$onDidChangeWebviewPanelViewStates (vscode-file://vscode…onHostProcess.js:95)
	at i._doInvokeHandler (vscode-file://vscode…onHostProcess.js:98)
	at i._invokeHandler (vscode-file://vscode…onHostProcess.js:98)
	at i._receiveRequest (vscode-file://vscode…onHostProcess.js:98)
	at i._receiveOneMessage (vscode-file://vscode…onHostProcess.js:98)
	at vscode-file://vscode…onHostProcess.js:98
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at l.fire (vscode-file://vscode…onHostProcess.js:74)
	at vscode-file://vscode…nHostProcess.js:113
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at l.fire (vscode-file://vscode…onHostProcess.js:74)
	at u._receiveMessage (vscode-file://vscode…onHostProcess.js:74)
	at vscode-file://vscode…onHostProcess.js:74
	at a.fire (vscode-file://vscode…onHostProcess.js:66)
	at v.acceptChunk (vscode-file://vscode…onHostProcess.js:74)
	at vscode-file://vscode…onHostProcess.js:74
	at Socket.w (vscode-file://vscode…nHostProcess.js:113)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///home/fabio_HD/Projetos/VSCode-linux-x64/resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///home/fabio/.vscode/extensions/dart-code.dart-code-3.27.2/syntaxes/dart.json
24
[Violation] 'setTimeout' handler took <N>ms
main.js:837 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
[Violation] Forced reflow while executing JavaScript took 36ms
﻿
​

**Comment by rangav** [comment]
Thanks @camposFabio for the issue, can you share a screenshot of the issue

**Comment by mjl** [comment]
Same problem here, under macos. 

Stack trace is exactly the same, when selecting "new request" from the command palette, an empty view with name "New Request" opens and nothing happens.

**Comment by rangav** [comment]
Could be issue with latest version of vscode.

can you downgrade to previous version and test it.

**Comment by camposFabio** [comment]
Don´t know what happened. Its working now on Arch. Maybe it needed an restart? Strange

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
