### ISSUE TITLE
TypeError: Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by Mr-KayJayDee** [rangav/thunder-client-support#444]
**Describe the bug**
Cannot open thunder client (new request)
**To Reproduce**

- Installl vscode 1.63.2
- Install thunder client
- CTRL + SHIFT + P > Thunder Client new request

**Expected behavior**
Display the request form

**Platform:** 
 - OS: MacOS Monterey 12.1
 - vscode version: 1.63.2
 - extension version: v1.9.1

**Solution:**
Not found...

**Full error:**

```js
TypeError: Cannot read property 'findOne' of undefined
    at Function.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:210277)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209607
    at new Promise (<anonymous>)
    at n (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:209352)
    at Function.da (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:210222)
    at Function.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:164099)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163496
    at new Promise (<anonymous>)
    at n (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:163241)
    at Function.Et (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:164048)
    at t.default.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8370)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
    at new Promise (<anonymous>)
    at s (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
    at t.default.jt (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8184)
    at t.default.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8838)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
    at new Promise (<anonymous>)
    at s (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
    at t.default.bt (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:8504)
    at t.default.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7783)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7201
    at new Promise (<anonymous>)
    at s (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:6946)
    at t.default.Ce (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:7526)
    at t.default.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:4319)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1499
    at new Promise (<anonymous>)
    at s (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1244)
    at t.default.je (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:4068)
    at t.default.<anonymous> (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:3568)
    at Generator.next (<anonymous>)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1499
    at new Promise (<anonymous>)
    at s (/Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:1244)
    at /Users/HIDDEN/.vscode/extensions/rangav.vscode-thunder-client-1.9.1/dist/extension.js:1:3523
    at r._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31080)
    at r.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31622)
    at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13802)
    at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13486)
    at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12148)
    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10826)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8922
    at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34341
    at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)
    at n._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:23523)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21057
    at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at w.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15770)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14900
    at Socket.T (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:13813)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by rangav** [comment]
Hi @Mr-KayJayDee thanks for reporting the bug. I will verify it.

I am using the same version of vscode on mac, its working for me. 

Can you close and re-start vscode and try again.

**Comment by Mr-KayJayDee** [comment]
Already did that and the issue was still there, i just re done it and still nothing. Just a black screen with the New request tab

**Comment by rangav** [comment]
may be try downgrading vscode to 1.63.0

**Comment by Mr-KayJayDee** [comment]
Same error on 1.62.0

**Comment by rangav** [comment]
try clicking Thunder Client icon on the `sidebar` and then click `New Request` button, let me know if you are getting same error.

**Comment by Mr-KayJayDee** [comment]
Alright now it works and after doing that i re tried with command palette and it works... Weird...

Thanks anyway

**Comment by rangav** [comment]
Thanks @Mr-KayJayDee for confirmation, some users are facing similar issues, don't know why.
