### ISSUE TITLE
convert export collection from v1.1 to v2 for postman

### ISSUE THREAD

**Issue by ToqaDev91** [rangav/thunder-client-support#530]
**Describe the bug**
I'm trying to export collection from vscode using thunder-client to be imported for postman , the json file created contains `"version":"1.1"` key , and when trying to convert using `postman-collection-transformer` package it's display either empty items or not converted

**To Reproduce**

 - export from vscode thunder bird with data: 
    ex : thunder-collection_stream_postman.json 
- convert using `postman-collection-transformer` :
`   postman-collection-transformer convert -i thunder-collection_stream.json -o thunder-collection_stream2.json -j 1.0.0 -p 2.0.0 -P`
  file created with no items 
 
 Note : 
   also tried this : 
    `   postman-collection-transformer convert -i thunder-collection_stream.json -o thunder-collection_stream2.json -j 1.1 -p 2.0.0 -P`
  and this error occurred : 
   ```
 Unable to convert the input: Error: Input version not specified or invalid: 1.1
    at Object.convert (/usr/local/lib/node_modules/postman-collection-transformer/lib/index.js:23:29)
    at Command.<anonymous> (/usr/local/lib/node_modules/postman-collection-transformer/bin/transform-collection.js:84:28)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:488:17)
    at /usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1193:19)
    at Command.parse (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:897:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/postman-collection-transformer/bin/transform-collection.js:141:9)
toqaabbas@Admins-MacBook-Pro-2 theqar_vagrant % postman-collection-transformer convert -i /Users/toqaabbas/Desktop/thunder-collection_stream.json -o /Users/toqaabbas/Desktop/thunder-collection_stream22.json -j 1.1.0 -p 2.0.0 -P
Unable to convert the input: Error: no conversion path found
    at Object.convert (/usr/local/lib/node_modules/postman-collection-transformer/lib/converters/index.js:100:29)
    at Object.convert (/usr/local/lib/node_modules/postman-collection-transformer/lib/index.js:26:26)
    at Command.<anonymous> (/usr/local/lib/node_modules/postman-collection-transformer/bin/transform-collection.js:84:28)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:488:17)
    at /usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:1193:19)
    at Command.parse (/usr/local/lib/node_modules/postman-collection-transformer/node_modules/commander/lib/command.js:897:10)
```

**Expected behavior**
 I expect to view requests in` items ` after converting to v2.0.0 for the postman

**Platform:** 
 - OS: MacOs Monterey v12.3
 - vscode version: 1.64.2
 - extension version: 1.14.4

**Comment by rangav** [comment]
Hi @ToqaDev91 thanks for contacting us.

Here are the steps to convert Thunder Client collection to Postman
https://github.com/rangav/thunder-client-support#how-to-convert-to-postman-format

**Comment by ToqaDev91** [comment]
Thank you @rangav for your immediate answer , when i did the steps you mention I got this in postman :

<img width="1392" alt="Screen Shot 2022-04-04 at 9 59 27 AM" src="https://user-images.githubusercontent.com/63723710/161490696-c65485f4-1543-4a0a-9eaa-c0244ff65eff.png">

then I tried to do the steps in [this](https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#converting-postman-collections-from-v1-to-v2) , 
But since the json file I got contains version "1.1" & this conversion from "1.0.0" , I got empty items array & not loaded in postman also

**Comment by rangav** [comment]
Can you share any sample collection files you converted?, I will verify

**Comment by ToqaDev91** [comment]
yes sure 
[collection.txt](https://github.com/rangav/thunder-client-support/files/8407907/collection.txt)

**Comment by rangav** [comment]
Its working for me, I think you not following the steps correctly.

<img width="828" alt="Screenshot 2022-04-04 at 09 58 32" src="https://user-images.githubusercontent.com/8637550/161510150-d460bc84-8a4d-4286-a864-17f6f5dd1198.png">

**Comment by rangav** [comment]
After you exported the thunder client collection file.
convert to postman format, it will convert to 2.0 format, see blow image

<img width="296" alt="Screenshot 2022-04-04 at 09 59 46" src="https://user-images.githubusercontent.com/8637550/161510539-afbcf266-cba1-43b1-ac13-e1c7933a3d2f.png">

Then you will get this file

[collection_postman.txt](https://github.com/rangav/thunder-client-support/files/8408262/collection_postman.txt)

**Comment by rangav** [comment]
you **`don't`** need this cli convertion - `postman-collection-transformer convert...... `

**Comment by ToqaDev91** [comment]
Thank you very much , really appreciate your patience

**Comment by rangav** [comment]
@ToqaDev91 no problem,  I hope its working for you now, closing the issue, feel free to re-open if needed.
